<?php

/*
function tavarat_kiertoon_commerce_product_search_api_saved_searches_new_results_alter(array &$results, SearchApiSavedSearch $search) {
  watchdog('saved_searches_commerce_product', json_encode($results));
  watchdog('saved_searches_commerce_product', json_encode($search));
  return;
}
*/

function tavarat_kiertoon_commerce_product_commerce_product_uri($product) {
  $u=sprintf('/product/%s', $product->sku);

  return array('path'=>$u, 'options'=>array());
}
